import { defineType, defineField, defineArrayMember } from 'sanity'

export const doctor = defineType({
  name: 'doctor',
  title: 'طبيب / Doctor',
  type: 'document',
  groups: [
    { name: 'identity', title: 'الهوية' },
    { name: 'profile', title: 'المعلومات المهنية' },
    { name: 'schedule', title: 'المواعيد' },
    { name: 'flags', title: 'الإعدادات' },
  ],
  fields: [
    defineField({
      name: 'name',
      type: 'localizedString',
      title: 'الاسم (بدون اللقب)',
      group: 'identity',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'slug',
      type: 'slug',
      title: 'الـ slug',
      group: 'identity',
      options: { source: 'name.en', maxLength: 80 },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'titlePrefix',
      type: 'localizedString',
      title: 'اللقب (د. / Dr.)',
      group: 'identity',
    }),
    defineField({
      name: 'specialty',
      type: 'localizedString',
      title: 'التخصص',
      group: 'profile',
    }),
    defineField({
      name: 'department',
      type: 'reference',
      to: [{ type: 'department' }],
      title: 'القسم',
      group: 'identity',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'photo',
      type: 'image',
      title: 'الصورة الشخصية',
      options: { hotspot: true },
      group: 'identity',
    }),
    defineField({
      name: 'gender',
      type: 'string',
      title: 'الجنس',
      group: 'identity',
      options: {
        list: [
          { title: 'ذكر / Male', value: 'male' },
          { title: 'أنثى / Female', value: 'female' },
        ],
        layout: 'radio',
      },
    }),
    defineField({
      name: 'nationality',
      type: 'string',
      title: 'الجنسية',
      group: 'identity',
      options: {
        list: [
          { title: 'سعودي', value: 'sa' },
          { title: 'مصري', value: 'eg' },
          { title: 'أردني', value: 'jo' },
          { title: 'سوداني', value: 'sd' },
          { title: 'هندي', value: 'in' },
          { title: 'باكستاني', value: 'pk' },
          { title: 'سوري', value: 'sy' },
          { title: 'لبناني', value: 'lb' },
        ],
      },
    }),
    defineField({
      name: 'languages',
      type: 'array',
      title: 'اللغات',
      group: 'profile',
      of: [{ type: 'string' }],
      options: {
        list: [
          { title: 'عربي', value: 'ar' },
          { title: 'إنجليزي', value: 'en' },
          { title: 'فرنسي', value: 'fr' },
          { title: 'أردو', value: 'ur' },
          { title: 'تركي', value: 'tr' },
        ],
      },
    }),
    defineField({
      name: 'yearsExperience',
      type: 'number',
      title: 'سنوات الخبرة',
      group: 'profile',
      validation: (Rule) => Rule.min(0),
    }),
    defineField({
      name: 'bio',
      type: 'localizedRichText',
      title: 'السيرة الذاتية',
      group: 'profile',
    }),
    defineField({
      name: 'qualifications',
      type: 'array',
      title: 'الشهادات والمؤهلات',
      group: 'profile',
      of: [defineArrayMember({ type: 'localizedString' })],
    }),
    defineField({
      name: 'workingDays',
      type: 'array',
      title: 'أيام العمل',
      group: 'schedule',
      of: [{ type: 'string' }],
      options: {
        list: [
          { title: 'الأحد / Sunday', value: 'sun' },
          { title: 'الإثنين / Monday', value: 'mon' },
          { title: 'الثلاثاء / Tuesday', value: 'tue' },
          { title: 'الأربعاء / Wednesday', value: 'wed' },
          { title: 'الخميس / Thursday', value: 'thu' },
          { title: 'الجمعة / Friday', value: 'fri' },
          { title: 'السبت / Saturday', value: 'sat' },
        ],
      },
    }),
    defineField({
      name: 'workingHours',
      type: 'localizedString',
      title: 'ساعات العمل (وصف مختصر)',
      group: 'schedule',
      description: 'مثال: 10 صباحاً - 6 مساءً / 10 AM – 6 PM',
    }),
    defineField({
      name: 'isAvailable',
      type: 'boolean',
      title: 'متاح للحجز حالياً',
      initialValue: true,
      group: 'flags',
    }),
    defineField({
      name: 'isFeatured',
      type: 'boolean',
      title: 'طبيب مميّز',
      initialValue: false,
      group: 'flags',
    }),
    defineField({
      name: 'displayOrder',
      type: 'number',
      title: 'ترتيب العرض',
      initialValue: 100,
      group: 'flags',
    }),
  ],
  preview: {
    select: { title: 'name', subtitle: 'specialty', media: 'photo' },
    prepare: ({ title, subtitle, media }) => ({
      title: title?.ar || title?.en || 'بدون اسم',
      subtitle: subtitle?.ar || subtitle?.en || '',
      media,
    }),
  },
  orderings: [
    {
      title: 'ترتيب العرض',
      name: 'displayOrder',
      by: [{ field: 'displayOrder', direction: 'asc' }],
    },
    {
      title: 'الأقدمية',
      name: 'experience',
      by: [{ field: 'yearsExperience', direction: 'desc' }],
    },
  ],
})
